name: Build
on:
  push:
    branches:
      - main
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set up Docker metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
          # This is configured as a repository variable
          images: |
            my-image/app
          tags: |
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}
      - run: echo ${{ steps.meta.outputs.tags }} ${{ steps.meta.outputs.labels }}
