name: Deploy ${{ github.ref }}
on:
  push:
    tags:
      - v*
jobs:
  deploy:
    name: Deploy Job
    uses: ./.github/workflows/do-it.yml
    with:
      sha: ${{ github.sha }}
      image_name: from_caller
