name: Deploy action
concurrency: ${{ github.workflow }}-${{ inputs.environment }}
on:
  workflow_call:
    inputs:
      tag:
        description: Tag to deploy
        type: string
        default: ''
        required: true
      environment:
        description: Environment
        type: string
        default: test
        required: false
jobs:
  deploy:
    name: Deploy to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - run: echo "Deploy ${{ inputs.tag }} to ${{ inputs.environment }}"
