name: Deploy action
concurrency: ${{ github.workflow }}-${{ inputs.environment }}
on:
  workflow_call:
    inputs:
      sha:
        description: SHA to deploy, if not HEAD
        type: string
        default: ''
        required: false
      environment:
        description: Environment
        type: string
        default: test
        required: false
jobs:
  deploy:
    name: Deploy to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - run: echo 'Deploy ${{ inputs.sha }} to ${{ inputs.environment }}'
