name: Deploy Workflow
concurrency: ${{ github.sha }}
env:
  SHA: "${{ inputs.sha || github.event.workflow_run.head_sha }}"
on:
  workflow_run:
    workflows: [Build]
    types:
      - completed
  workflow_dispatch:
    inputs:
      sha:
        description: SHA to deploy, if not HEAD
        type: string
        default: ''
        required: false
      image_name:
        description: Image name
        type: string
        default: ''
        required: false
  workflow_call:
    inputs:
      sha:
        description: SHA to deploy, if not HEAD
        type: string
        default: ''
        required: false
      image_name:
        description: Image name
        type: string
        default: ''
        required: false
jobs:
  echo:
    name: "Echo job"
    runs-on: ubuntu-latest
    steps:
      - name: Create annotation for build error
        run: echo "::notice::SHA ${{ github.sha }}, REF ${{ github.ref }}", INPUT ${{ inputs.sha || github.sha }} IMAGE_NAME ${{ inputs.image_name }}
      - name: another step
        run: echo "im just another step in the machine"
  echo2:
    name: "Echo 2 job"
    runs-on: ubuntu-latest
    steps:
      - name: another job
        run: echo "another job!"
  echo3:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow passed with head SHA ${{ github.event.workflow_run.head_sha }}'
