name: Deploy Workflow
env:
  SHA: "${{ inputs.sha || github.event.workflow_run.head_sha || github.sha }}"
on:
  # Production deployment: SHA is from `github.sha`
  push:
    tags:
      - v*

  # Staging deployment: SHA is from github.event.workflow_run.head_sha
  workflow_run:
    workflows: [Build]
    types:
      - completed

  # Explicit deployment: SHA is from input
  workflow_dispatch:
    inputs:
      sha:
        description: SHA to deploy, if not HEAD
        type: string
        default: ''
        required: false
      image_name:
        description: Image name
        type: string
        default: ''
        required: false
      environment:
        description: Environment
        type: environment
        default: test
        required: false
jobs:
  set-inputs:
    name: "Set inputs"
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.environment.outputs.environment }}
      sha: ${{ steps.sha.outputs.sha }}
      short_sha: ${{ steps.short-sha.outputs.short_sha }}
    steps:
      - uses: actions/checkout@v4
      - id: environment
        run: echo "environment=${{ inputs.environment || (github.event_name == 'push' && startsWith(github.ref, 'refs/tags') && 'production') || 'test' }}" >> "$GITHUB_OUTPUT"
      - id: sha
        run: echo "sha=${{ inputs.sha || github.event.workflow_run.head_sha || github.sha }}" >> "$GITHUB_OUTPUT"
      - id: short-sha
        run: echo "short_sha=$(git rev-parse --short ${{ steps.sha.outputs.sha }})" >> "$GITHUB_OUTPUT"
  # echo:
  #   name: "Echo job"
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Create annotation for build error
  #       run: echo "::notice::SHA ${{ env.SHA }}"
  #     - id: short_sha
  #       run: echo "short_sha=$(git rev-parse --short )"
  # echo2:
  #   name: "Echo 2 job"
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: another job
  #       run: echo "another job!"
  # Dispatch
  deploy:
    name: Deploy
    uses: ./.github/workflows/deploy-action.yml
    needs: set-inputs
    with:
      environment: ${{ needs.set-inputs.outputs.environment }}
      tag: ${{ needs.set-inputs.outputs.short_sha }}

    # name: Deploy to
    # runs-on: ubuntu-latest
    # environment: ${{ inputs.environment || (github.event_name === 'push' && 'production') || 'test' }}
    # concurrency: ${{ github.workflow }}-${{ inputs.environment || (github.event_name === 'push' && 'production') || 'test' }}

    # steps:
    #   - run: echo 'Deploying to was called ${{ inputs.environment }}'
  # # Automated staging deployments
  # deploy-production:
  #   runs-on: ubuntu-latest
  #   if: ${{ github.event_name == 'push' }}
  #   environment: production
  #   steps:
  #     - run: echo 'The production job was triggered'
  # deploy-staging:
  #   runs-on: ubuntu-latest
  #   if: ${{ github.event.workflow_run.conclusion == 'success' }}
  #   environment: test
  #   steps:
  #     - run: echo 'The triggering workflow passed with head SHA ${{ github.event.workflow_run.head_sha }}'
