on:
  push:
    branches:
      - main
    tags:
      - v*
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Create annotation for build error
        run: echo "::notice::SHA ${{ github.sha }}, REF ${{ github.ref }}"
